# Generated by Django 5.1.6 on 2025-03-05 15:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_add_usergamestats_existing_users"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UserProfile",
        ),
    ]
