# Generated by Django 5.1.6 on 2025-03-09 21:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_delete_userprofile"),
    ]

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField()),
                ("applicable_squares", models.JSONField(default=list)),
                ("score_to_award", models.IntegerField(default=10)),
            ],
        ),
    ]
