# Generated by Django 5.1.6 on 2025-03-10 01:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0005_task"),
    ]

    operations = [
        migrations.AddField(
            model_name="usergamestats",
            name="current_task",
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name="usergamestats",
            name="task_completed",
            field=models.BooleanField(default=False),
        ),
    ]
