name: Run frontend tests

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: node:20
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2  
        with:
          node-version: 20

      - name: Install packages from package-lock.json
        run: |
          cd application
          npm ci

      - name: Check for jest environment
        run: |
          cd application
          npm install --save-dev jest jest-environment-jsdom

      - name: Run JEST tests
        run: |
          cd application
          npx jest --clearCache
          npm test